# Generated by Django 4.1 on 2022-12-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_change', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price_change',
            name='description',
            field=models.TextField(default='default title'),
        ),
    ]
