# Generated by Django 4.1 on 2022-12-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_change', '0002_price_change_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_change',
            name='file',
            field=models.FileField(upload_to='files/'),
        ),
    ]
