# Generated by Django 4.1 on 2022-12-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_change', '0003_alter_price_change_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_change',
            name='file',
            field=models.FileField(upload_to='price_change/files/'),
        ),
    ]
