# Generated by Django 4.1 on 2022-12-16 11:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_change', '0004_alter_price_change_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_change',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
